config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get '/language', to: "users#change_language"
  scope "(:locale)", locale: /en|nl/ do
    resources :users, only: [ :new, :create, :index, :destroy ]
  end
  # scope "(:locale)", locale: /en|nl/ do
  #   resources :books
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, 
    format: { 
      with: /\A[a-zA-Z]+\z/
    }
  validates :email, 
    uniqueness: true,
    presence: true
  validates :contact, 
    length: { is: 10 }
  validates :age, :contact, 
    numericality: { 
      only_integer: true, 
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  before_action :set_locale

  def set_locale
    I18n.locale = cookies[:locale] || I18n.default_locale
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def change_language
    if cookies[:locale].eql?("en")
      cookies[:locale] = "nl" 
    else
      cookies[:locale] = "en"  
    end
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit( 
        :name,
        :contact,
        :email,
        :age 
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_error(model,field)
    error_messages = model.errors.full_messages_for(field)
    unless error_messages.empty?
      field = model.class.human_attribute_name(field)
      error_messages.each do |message|
        puts "<div class='alert alert-danger'>#{message}</div>"
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoI18n</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
      crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container text-center">
<h2> <%= t(:hello)%> Users </h2>
  <div class="row justify-content-md-center">
    <%= link_to "#{t(:add_user)}", new_user_path %><br><br>
    <%= link_to "#{t(:change_language)}", language_path %><br><br>    
    <div class="col">
      <table class="table table-striped">
        <thead>
          <tr>  
            <th scope="col"> <%= t(:id) %> </th>
            <th scope="col"> <%= t(:name) %> </th>
            <th scope="col"> <%= t(:email) %> </th>
            <th scope="col"> <%= t(:contact) %> </th>
            <th scope="col"> <%= t(:age) %> </th>
            <th scope="col"> <%= t(:action) %> </th>     
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user|  %>
            <tr>
              <td> <%= user.id %> </td>
              <td> <%= user.name %> </td>
              <td> <%= user.email %> </td>
              <td> <%= user.contact %> </td>
              <td> <%= user.age %> </td>
              <td> <%= link_to t(:delete), user_path(id: user),
                data: { 
                  turbo_method: :delete
                  } ,
                  class: "btn btn-primary" %> 
              </td> 
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>
  <div class="container">
    <h2 class="text-center"> <%= t(:add_user) %> </h2>
    <div class="row">  
      <div class="col-4">
        <%= form.label "#{t(:name)}" %>
        <%= form.text_field :name, class: "form-control" %>
        <%= custom_error(@user, :name) %><br>
      </div>
    </div><br/>

    <div class="row">  
      <div class="col-4">
        <%= form.label "#{t(:email)}" %>
        <%= form.email_field :email, class: "form-control" %><br>
        <%= custom_error(@user, :email) %><br>
      </div>
    </div><br/>

    <div class="row">  
      <div class="col-4">
        <%= form.label "#{t(:contact)}" %>
        <%= form.text_field :contact, class: "form-control" %> <br>
        <%= custom_error(@user, :contact) %><br>
      </div>
    </div><br/>

    <div class="row">  
      <div class="col-4">
        <%= form.label "#{t(:age)}" %>
        <%= form.number_field :age, class: "form-control" %> <br>
        <%= custom_error(@user, :age) %><br>
      </div>
    </div><br/>

    <div>
      <%= form.submit "#{t(:insert)}", class: "btn btn-primary" %>
    </div>

  </div>
<% end %>